# Generated by Django 4.2.2 on 2024-09-24 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        help_text="Укажите наименование категории услуги",
                        max_length=50,
                        verbose_name="Категория услуги",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Укажите описание категории услуги",
                        null=True,
                        verbose_name="Описание категории услуги",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение товара",
                        null=True,
                        upload_to="services/",
                        verbose_name="Изображение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ("category_name",),
            },
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "services_name",
                    models.CharField(
                        help_text="Укажите наименование услуги",
                        max_length=50,
                        verbose_name="Наименование услуги",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Укажите описание услуги",
                        null=True,
                        verbose_name="Описание услуги",
                    ),
                ),
                (
                    "price",
                    models.IntegerField(
                        help_text="Укажите цену услуги", verbose_name="Цена услуги"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Выберите категорию услуги",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
                "ordering": ("services_name",),
            },
        ),
    ]
