# Generated by Django 4.2.2 on 2024-09-24 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doctor", "0001_initial"),
        ("services", "0001_initial"),
        ("record", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="result",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пациент",
            ),
        ),
        migrations.AddField(
            model_name="result",
            name="record",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="record.record",
                verbose_name="Запись",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="services.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="doctor.doctor",
                verbose_name="Врач",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="services",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="services.services",
                verbose_name="Услуга",
            ),
        ),
    ]
