# Generated by Django 4.2.2 on 2024-09-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Укажите Ф.И.О. врача",
                        max_length=100,
                        verbose_name="Ф.И.О",
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        help_text="Укажите специальность врача",
                        max_length=100,
                        verbose_name="Специальность",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Добавьте фото",
                        null=True,
                        upload_to="doctors/",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "experience",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Укажите стаж работы врача",
                        null=True,
                        verbose_name="Стаж",
                    ),
                ),
                (
                    "education",
                    models.TextField(
                        blank=True,
                        help_text="Укажите образование врача",
                        null=True,
                        verbose_name="Образование",
                    ),
                ),
            ],
            options={
                "verbose_name": "Врач",
                "verbose_name_plural": "Врачи",
            },
        ),
    ]
